### ISSUE TITLE
Fabric 1.19.3 使用AllMusic 1.19时有可能崩溃

### ISSUE THREAD

**Issue by WzczChenX** [Coloryr/AllMusic_Client#16]
崩溃前的log）
[22:41:29] [Render thread/INFO]: [CHAT] [AllMusic]空闲列表点歌27589787
[22:41:30] [Render thread/INFO]: [CHAT] [AllMusic]音乐列表添加-紅楼- | 狐の工作室 | 東方幻想界 -紅魔郷の音- 彩 | 
[22:41:30] [Render thread/INFO]: [CHAT] [AllMusic]正在播放：-紅楼- | 狐の工作室 | 東方幻想界 -紅魔郷の音- 彩 |  | by: 空闲列表
[22:41:41] [allmusic_run/INFO]: [STDERR]: java.net.UnknownHostException: 不知道这样的主机。 (m8.music.126.net)
[22:41:41] [allmusic_run/INFO]: [STDERR]: 	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
[22:41:41] [allmusic_run/INFO]: [STDERR]: 	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(Unknown Source)
[22:41:41] [allmusic_run/INFO]: [STDERR]: 	at java.base/java.net.InetAddress.getAddressesFromNameService(Unknown Source)
[22:41:41] [allmusic_run/INFO]: [STDERR]: 	at java.base/java.net.InetAddress$NameServiceAddresses.get(Unknown Source)
[22:41:41] [allmusic_run/INFO]: [STDERR]: 	at java.base/java.net.InetAddress.getAllByName0(Unknown Source)
[22:41:41] [allmusic_run/INFO]: [STDERR]: 	at java.base/java.net.InetAddress.getAllByName(Unknown Source)
[22:41:41] [allmusic_run/INFO]: [STDERR]: 	at java.base/java.net.InetAddress.getAllByName(Unknown Source)
[22:41:41] [allmusic_run/INFO]: [STDERR]: 	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45)
[22:41:41] [allmusic_run/INFO]: [STDERR]: 	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112)
[22:41:41] [allmusic_run/INFO]: [STDERR]: 	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
[22:41:41] [allmusic_run/INFO]: [STDERR]: 	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
[22:41:41] [allmusic_run/INFO]: [STDERR]: 	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
[22:41:41] [allmusic_run/INFO]: [STDERR]: 	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
[22:41:41] [allmusic_run/INFO]: [STDERR]: 	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
[22:41:41] [allmusic_run/INFO]: [STDERR]: 	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
[22:41:41] [allmusic_run/INFO]: [STDERR]: 	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
[22:41:41] [allmusic_run/INFO]: [STDERR]: 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
[22:41:41] [allmusic_run/INFO]: [STDERR]: 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
[22:41:41] [allmusic_run/INFO]: [STDERR]: 	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
[22:41:41] [allmusic_run/INFO]: [STDERR]: 	at coloryr.allmusic.player.APlayer.connect(APlayer.java:118)
[22:41:41] [allmusic_run/INFO]: [STDERR]: 	at coloryr.allmusic.player.APlayer.run(APlayer.java:137)
[22:41:41] [allmusic_run/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Unknown Source)
[22:41:41] [Render thread/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath: [jar:file:/E:/.minecraft/.minecraft/libraries/com/github/oshi/oshi-core/6.2.2/oshi-core-6.2.2.jar!/oshi.architecture.properties, jar:file:/E:/.minecraft/.minecraft/libraries/com/github/oshi/oshi-core/6.2.2/oshi-core-6.2.2.jar!/oshi.architecture.properties]
[22:41:41] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NoSuchMethodError: 'void net.minecraft.class_746.method_3142(java.lang.String)'
	at coloryr.allmusic.AllMusic.lambda$sendMessage$1(AllMusic.java:93) ~[%5Bfabric-1.19%5DAllMusic-2.6.3.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1144) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:781) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) ~[1.19.3-Fabric%200.14.11.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[1.19.3-Fabric%200.14.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.11.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58) ~[?:?]
	at oolloo.jlw.Wrapper.main(Wrapper.java:51) ~[?:?]
[22:41:42] [Render thread/INFO]: Minimap session finalized.
[22:41:42] [Render thread/INFO]: Finalizing world map session...
[22:41:42] [Thread-4/INFO]: World map force-cleaned!
[22:41:42] [Render thread/INFO]: World map session finalized.
[22:41:42] [Render thread/INFO]: Stopping worker threads
崩溃报告：
[Uploading crash-2022-12-25_22.41.42-client.txt…]()

**Comment by WzczChenX** [comment]
[crash-2022-12-25_22.41.42-client.txt](https://github.com/Coloryr/AllMusic_M/files/10300203/crash-2022-12-25_22.41.42-client.txt)

**Comment by WzczChenX** [comment]
crash-report:
---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 2022-12-25 22:41:42
Description: Unexpected error

java.lang.NoSuchMethodError: 'void net.minecraft.class_746.method_3142(java.lang.String)'
	at coloryr.allmusic.AllMusic.lambda$sendMessage$1(AllMusic.java:93)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)
	at net.minecraft.class_1255.method_5383(class_1255.java:115)
	at net.minecraft.class_310.method_1523(class_310.java:1144)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at coloryr.allmusic.AllMusic.lambda$sendMessage$1(AllMusic.java:93)
	at net.minecraft.class_1255.method_18859(class_1255.java:156)
	at net.minecraft.class_4093.method_18859(class_4093.java:23)
	at net.minecraft.class_1255.method_16075(class_1255.java:130)

-- Affected level --
Details:
	All players: 2 total; [class_746['zChenX'/35326582, l='ClientLevel', x=-19443.39, y=73.00, z=-29823.25], class_745['FlashFF'/35338831, l='ClientLevel', x=-19432.30, y=73.00, z=-29841.70]]
	Chunk stats: 1024, 201 F: 59 L: 0 U: 0
	Level dimension: minecraft:overworld
	Level spawn location: World: (85,63,277), Section: (at 5,15,5 in 5,3,17; chunk contains blocks 80,-64,272 to 95,319,287), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 175827 game time, 605569971 day time
	Server brand: Pufferfish
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:455)
	at net.minecraft.class_310.method_1587(class_310.java:2390)
	at net.minecraft.class_310.method_1514(class_310.java:805)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:58)
	at oolloo.jlw.Wrapper.main(Wrapper.java:51)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, Fabric Mods, file/Fixed_Textures_Java, file/Binyas_Shield_Fix, __MoreMcmeta Internal__

-- System Details --
Details:
	Minecraft Version: 1.19.3
	Minecraft Version ID: 1.19.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 326449496 bytes (311 MiB) / 1161822208 bytes (1108 MiB) up to 3758096384 bytes (3584 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: Zen 2
	Frequency (GHz): 4.20
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1050 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c82
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7168
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Virtual memory max (MB): 25550.80
	Virtual memory used (MB): 14624.94
	Swap memory total (MB): 17408.00
	Swap memory used (MB): 386.53
	JVM Flags: 6 total; -XX:+UseG1GC -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmn256m -Xmx3584m
	Fabric Mods: 
		adaptive-tooltips: Adaptive Tooltips 1.1.1
			com_github_llamalad7_mixinextras: mixinextras 0.1.1
		allmusic: AllMusic 2.6.3
		appleskin: AppleSkin 2.4.2+mc1.19.3
		architectury: Architectury 7.0.65
		axolotlitemfix: Axolotl Item Fix 1.1.4
		betterhurtcam: BetterHurtCam 1.5.2
			betterhurtcam-mc1193: BetterHurtCam+mc1.19.3 1.5.2
		betterpingdisplay: Better Ping Display 1.1.1
		bobby: Bobby 4.0.3
			com_typesafe_config: config 1.4.2
			fabric-api-base: Fabric API Base 0.4.19+8d1895cf72
			fabric-command-api-v2: Fabric Command API (v2) 2.1.15+49abcf7e72
			io_leangen_geantyref_geantyref: geantyref 1.3.13
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		carpet: Carpet Mod 1.4.91
		cem: Custom Entity Models 0.7.1
			completeconfig-base: completeconfig-base 2.2.0
			completeconfig-gui-cloth: completeconfig-gui-cloth 2.2.0
		chat_heads: Chat Heads 0.8.1
		clientcommands: Client Commands 2.7.7
			clientarguments: clientarguments 1.4.2
		cloth-config: Cloth Config v9 9.0.94
			cloth-basic-math: cloth-basic-math 0.6.1
		completeconfig: CompleteConfig 2.2.0
			coat: Coat 1.0.0-beta.19+mc22w44a
			completeconfig-gui-yacl: completeconfig-gui-yacl 2.2.0
		controlling: Controlling For Fabric 10.0+9
		customskinloader: CustomSkinLoader 14.15-SNAPSHOT-355
		detailab: Detail Armor Bar 2.6.3+1.19.3-fabric
		enchlevel-langpatch: Enchantment Level Language Patch 1.2.3
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19.3
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		fabric-api: Fabric API 0.69.1+1.19.3
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.18+49abcf7e85
			fabric-biome-api-v1: Fabric Biome API (v1) 12.0.0+689f5e7185
			fabric-block-api-v1: Fabric Block API (v1) 1.0.3+12bfe4ea85
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.28+c6af733c85
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.9+49abcf7e85
			fabric-command-api-v1: Fabric Command API (v1) 1.2.19+f71b366f85
			fabric-commands-v0: Fabric Commands (v0) 0.2.36+df3654b385
			fabric-containers-v0: Fabric Containers (v0) 0.1.44+df3654b385
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.4.12+49abcf7e85
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.0+8e4e694f85
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.12+aeb40ebe85
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 11.1.1+112a38be85
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.39+48349a3f85
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.5+b83334a085
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.37+422b77fb85
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.39+df3654b385
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.28+2894d6df85
			fabric-item-api-v1: Fabric Item API (v1) 2.1.5+4d2c606385
			fabric-item-group-api-v1: Fabric Item Group API (v1) 2.1.8+d3d735d085
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.28+aaaf9d3385
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.26+df3654b385
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.8+2894d6df85
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.18+75e9821185
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.22+9e7660c685
			fabric-message-api-v1: Fabric Message API (v1) 5.0.12+6ede1da985
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.29+49abcf7e85
			fabric-models-v0: Fabric Models (v0) 0.3.25+11ba9c3b85
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.14+d9ac3c3985
			fabric-networking-v0: Fabric Networking (v0) 0.3.31+df3654b385
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 5.2.0+e9dee00485
			fabric-particles-v1: Fabric Particles (v1) 1.0.18+fbde993d85
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 2.0.1+2608564685
			fabric-renderer-api-v1: Fabric Renderer API (v1) 2.1.0+2063beff85
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.23+11ba9c3b85
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.28+df3654b385
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.23+48349a3f85
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.16+3067f46385
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.31+df3654b385
			fabric-rendering-v1: Fabric Rendering (v1) 1.11.7+49abcf7e85
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.2.0+280be3ab85
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.10.3+a10d22bd85
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.39+1d4d0b5785
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.10+689f5e7185
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.6+75e9821185
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.12+82a2701785
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 2.1.0+0efcd39b85
		fabric-language-kotlin: Fabric Language Kotlin 1.8.7+kotlin.1.7.22
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.22
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.22
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.22
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.5
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.4
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.4
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.4.1
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.4.1
		fabricloader: Fabric Loader 0.14.11
		fastload: Fast Load 2.6.7
		ferritecore: FerriteCore 5.1.0
		gammautils: Gamma Utils 1.6.12
		hatlist: Hat List 1.4
		held-item-info: Held Item Info 1.4.1
		ias: In-Game Account Switcher 8.0.1.1
		ibeeditor: IBE Editor 2.2.2
		immediatelyfast: ImmediatelyFast 1.0.7
		indium: Indium 1.0.10+mc1.19.3
		inventoryprofilesnext: Inventory Profiles Next 1.8.6
		isometric-renders: Isometric Renders 0.4.1+1.19.3
			worldmesher: Worldmesher 0.2.14+1.19.3
		itemscroller: Item Scroller 0.18.0
		jade: Jade 9.2.1
		java: OpenJDK 64-Bit Server VM 17
		kappa: Kappa 3.0.4
		languagereload: Language Reload 1.5
		lazydfu: LazyDFU 0.1.3
		libipn: libIPN 1.0.8
		litematica: Litematica 0.13.0
		lithium: Lithium 0.10.4
		lowfire: Low Fire 1.19.3-3.0.1
		magiclib: MagicLib 0.6.194+3df5798-beta
			magiclib-1_19_3: MagicLib for 1.19.3 0.6.194+3df5798-beta
		malilib: MaLiLib 0.14.0
		mcwifipnp: LAN World Plug-n-Play 1.6.3
		memoryleakfix: memory Leak Fix 1.19.3-0.7.0
		minecraft: Minecraft 1.19.3
		minihud: MiniHUD 0.25.0
		mixin-conflict-helper: Mixin Conflict Helper 1.2.0
		modmenu: Mod Menu 5.0.2
		morechathistory: MoreChatHistory 1.1.1
		moreculling: More Culling 1.19.3-0.12.3
			conditional-mixin: conditional mixin 0.3.2
		moremcmeta: MoreMcmeta 1.19.3-3.0.5
		nochatreports: No Chat Reports 1.19.3-v1.19.0
		norefreshscroll: NoRefreshScroll 1.0.3
		owo: oωo 0.9.3+1.19.3
			blue_endless_jankson: jankson 1.2.1
		reeses-sodium-options: Reese's Sodium Options 1.4.9+mc1.19.2-build.67
		skinpr: SkinPartsRefresher 1.0.3
		smoothboot: Smooth Boot 1.19-1.7.1
		sodium: Sodium 0.4.6+build.20
		sodium-extra: Sodium Extra 0.4.14+mc1.19.3-build.81
			caffeineconfig: CaffeineConfig 1.0.0+1.17
		spu: Server Pack Unlocker 1.3
		sspb: Sodium Shadowy Path Blocks 3.1.0
		starlight: Starlight 1.1.1+fabric.ae22326
		status-effect-bars: Status Effect Bars 1.0.2
		subtitle-highlight: 字幕高亮 3
		symbol-chat: Symbol Chat 1.19.3-0.6.0
		totemcounter: TotemCounter 1.1.0+mc1.19.3
		tweakermore: TweakerMore 3.9.2
		tweakeroo: Tweakeroo 0.15.0
		tweakmyclient: Tweak My Client 3.4.300+25ba527-beta
			tweakmyclient-1_19_3: Tweak My Client for 1.19.3 3.4.300+25ba527-beta
		uglyscoreboardfix: Ugly Scoreboard Fix 2.7.0
		ukulib: ukulib 0.4.0+1.19.3
			com_moandjiezana_toml_toml4j: toml4j 0.7.2
			gs_mclo_java_mclogs-java: mclogs-java 2.1.1
		viafabric: ViaFabric 0.4.9+22-main
			org_yaml_snakeyaml: snakeyaml 1.33
			viafabric-mc119: ViaFabric for 1.19 0.4.9+22-main
			viaversion: ViaVersion 4.5.0
		xaerominimap: Xaero's Minimap 22.17.0
		xaeroworldmap: Xaero's World Map 1.28.4
		yet-another-config-lib: YetAnotherConfigLib 2.1.1
		zoomify: Zoomify 2.9.2
			com_akuleshov7_ktoml-core-jvm: ktoml-core-jvm 0.3.0
			dev_isxander_settxi_settxi-core: settxi-core 2.10.6
			dev_isxander_settxi_settxi-gui: settxi-gui 2.10.6
			dev_isxander_settxi_settxi-kotlinx-serialization: settxi-kotlinx-serialization 2.10.6
			settxi-gui-yacl: Settxi Gui (YetAnotherConfigLib) 2.10.6
	Launched Version: 1.19.3-Fabric 0.14.11
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1050 Ti/PCIe/SSE2 GL version 3.2.0 NVIDIA 471.68, NVIDIA Corporation
	Window size: 2560x1334
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'
	Type: Client (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, fabric, file/Fixed_Textures_Java (incompatible), file/Binyas_Shield_Fix (incompatible)
	Current Language: 简体中文 (中国大陆)
	CPU: 12x AMD Ryzen 5 3600 6-Core Processor

**Comment by Coloryr** [comment]
使用1.19.3版本
